### ISSUE TITLE
TelephonyManager.getNetworkType() requires READ_PHONE_STATE permission for API level 30

### ISSUE THREAD

**Issue by Bakeneko** [mapbox/mapbox-events-android#482]
[TelephonyManager.getNetworkType()](https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkType()) is deprecated and requires dangerous READ_PHONE_STATE permission for API level 30.

**Configuration**
 Android OS Version 11

**Steps to Reproduce**
1. Target API level 30
2. Build and launch app
3. Load a MapView

**Expected**
Display a MapView

**Actual behavior**
Crash the app :

```
Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8711)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2945)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2909)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:150)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:277)
```

**Workaround**
Handle READ_PHONE_STATE runtime permission before using MapView.

**Comment by SamStenner** [comment]
This is a pretty serious bug, and will produce privacy concerns from users if not fixed. Any app that accesses location already requires the trust of the user, and requesting access to extraneous permissions will hurt that trust.

**Comment by fards** [comment]
Just to clarify:
This isn't just an issue with compiling the sdk ( I had a colleague suggest it might be). 
 Every app that uses mapbox, errors out on Android 11 with the same logs.
This is Strava for example, rwgps, even meteo weatherpro does the same. 
As we're rapidly heading towards a release of A11, this needs fixing fairly quickly and out beta testing. Otherwise there will be a lot of mapbox clients having to deal with irate customers. 

> ``
java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8722)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2958)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2922)
	at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(ProGuard:2)
	at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(ProGuard:6)
	at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(ProGuard:4)
	at com.mapbox.mapboxsdk.maps.MapView.h(ProGuard:2)
	at com.mapbox.mapboxsdk.maps.SupportMapFragment.onViewCreated(ProGuard:2)
	at o0.o.d.p.X(ProGuard:95)
	at o0.o.d.p.V(ProGuard:4)
	at o0.o.d.p.W(ProGuard:6)
	at o0.o.d.a.s(ProGuard:28)
	at o0.o.d.p.E(ProGuard:51)
	at o0.o.d.p.f0(ProGuard:10)
	at o0.o.d.p.C(ProGuard:14)
	at o0.o.d.p.w(ProGuard:5)
	at o0.o.d.c.onStart(ProGuard:9)
	at o0.b.k.k.onStart(ProGuard:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
	at android.app.Activity.performStart(Activity.java:8110)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3523)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7869)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by LocusLabsGit** [comment]
@fards I can confirm the error happens at runtime not at compile time.

**Comment by nagineni** [comment]
Fixed in release version 6.1.0 - https://github.com/mapbox/mapbox-events-android/releases/tag/telem-6.1.0-core-3.0.0

**Comment by nagineni** [comment]
Maps SDK integration PR here - https://github.com/mapbox/mapbox-gl-native-android/pull/527

**Comment by another-dave** [comment]
Running against Android 10, we're using `com.mapbox.mapboxsdk:mapbox-android-sdk:9.4.0` which I think includes the correct version of Telemetry for the fix above, but we're still seeing a logged error for this:

```
E/TelemetryUtils: java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10864 does not have android.permission.READ_PHONE_STATE.
```

**Comment by nagineni** [comment]
@another-dave :wave:

> E/TelemetryUtils: java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10864 does not have android.permission.READ_PHONE_STATE.

We see that error in the logs if the READ_PHONE_STATE permission is handled at runtime or the permission is not granted by the user.

**Comment by another-dave** [comment]
> @another-dave 👋
> 
> > E/TelemetryUtils: java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10864 does not have android.permission.READ_PHONE_STATE.
> 
> We see that error in the logs if the READ_PHONE_STATE permission is handled at runtime or the permission is not granted by the user.

Hi @nagineni, thanks for getting back. So I think this error can be safely ignored, but just want to double-check? or is `READ_PHONE_STATE` a required permission?

**Comment by nagineni** [comment]
The error message in the logs can be ignored since it is thrown only when there is no READ_PHONE_STATE permission granted. READ_PHONE_STATE permission is required to get the data network type using new API i.e getDataNetworkType(). In case if the user has not provided READ_PHONE_STATE and handled permissions at runtime, the value of the data network will be [network type unknown](https://developer.android.com/reference/android/telephony/TelephonyManager#NETWORK_TYPE_UNKNOWN).
